### ISSUE TITLE
Too many beams

### ISSUE THREAD

**Issue by wgmilleriii** [craigsapp/humextra#18]
[Archive.zip](https://github.com/craigsapp/humextra/files/5779459/Archive.zip)
See attached - hum2xml creates extra <beam> (32nd note beam created for 16th note). Compiled on Mac.

**Comment by craigsapp** [comment]
There was a problem in the Humdrum data for the file:

<img width="138" alt="Screen Shot 2021-01-06 at 10 13 58 PM" src="https://user-images.githubusercontent.com/3487289/103858274-e397d280-506c-11eb-80ba-d81d2474266e.png">

The `g` note has a beam start (`L`) as expected, but then the following `cc` should have only one `L` for a new beam for the 16th notes.  The file you give was last edited in 2008, but I see that I fixed this beam in 2009, and the most recent version of the file is correct:

<img width="104" alt="Screen Shot 2021-01-06 at 10 14 17 PM" src="https://user-images.githubusercontent.com/3487289/103858791-d29b9100-506d-11eb-8b24-4b85eb3763c2.png">


https://verovio.humdrum.org/?file=chorales/chor006.krn

Where did you get the file?  I may have an old version of the files online somewhere that I should update.  Otherwise, you can get the most recent files from github at https://github.com/craigsapp/bach-370-chorales.

**Comment by wgmilleriii** [comment]
Sir Craig,
I'm extremely grateful for your work.
The errant file was from https://github.com/jthickstun/bach-371-chorales.. I grabbed yours and everything is golden now.
Best,
Chip

**Comment by craigsapp** [comment]
OK, I will see if John will update to the newest scores (not much has changed except small changes like this one).
