### ISSUE TITLE
[beat] Problems with tied notes

### ISSUE THREAD

**Issue by WolfgangDrescher** [craigsapp/humextra#22]
`beat` seems to have problems when the data tokens contain `]`.

Run `extractxx -k 1,4 | fb -ac | beat -a` on the example Bach chorales below. The numbers in front are line indices.

### chor081

<img width="332" alt="Bildschirmfoto 2023-11-13 um 15 28 00" src="https://github.com/craigsapp/humextra/assets/865594/085f16f5-5d25-4366-9ccf-a07a82d23607">

### chor113

<img width="327" alt="Bildschirmfoto 2023-11-13 um 15 25 46" src="https://github.com/craigsapp/humextra/assets/865594/479718db-1a23-4af5-85e5-5a536d37006c">

### chor123

<img width="340" alt="Bildschirmfoto 2023-11-13 um 15 22 49" src="https://github.com/craigsapp/humextra/assets/865594/e132c9f4-d595-4d8d-9f25-98c03224e362">

### chor346

<img width="335" alt="Bildschirmfoto 2023-11-13 um 15 30 51" src="https://github.com/craigsapp/humextra/assets/865594/27c30f30-6e45-4303-9455-728de3c3917b">

---

Also note the `beat` will swallow the first line of the chorales kern that contain `!!!!SEGMENT...`.

**Comment by craigsapp** [comment]
You need to add `-A 0` to the `beat` tool.  By default it will only output beat positions if there is at least one note-attack on the line.   In this case there are two secondary tied notes on the line, so it does not list the beat for that line.   This is so that metric information about note attacks can be extracted.

Adding `-A 0` means to also include beat positions for lines that have no note attacks:

`humcat h://chorales/chor081.krn | extractxx -k 1,4 | bin/fb -ac | beat -a -A 0`

<img width="354" alt="Screenshot 2023-11-14 at 05 43 16" src="https://github.com/craigsapp/humextra/assets/3487289/1ee7c753-2efb-47b7-8bd6-09ae2392f6e1">

Notice that every data line of the `**beat` data has a number, including null-token lines.  The null-token lines can be removed before doing the analysis if you don't want to analyze lines only containing null tokens (or an option can be added to avoid null-token `**kern` lines):

`humcat h://chorales/chor081.krn | extractxx -k 1,4 | rid -glid | bin/fb -ac | beat -a -A 0`

<img width="336" alt="Screenshot 2023-11-14 at 05 48 19" src="https://github.com/craigsapp/humextra/assets/3487289/0df9270b-b0a9-4c96-81b2-7b6a64e5a14e">

(`rid` = original Humdrum Toolkit tool, `ridx` = Humdrum Extras, `ridxx` = humlib in a similar manner as for `extract`, and `rid` within VHV is the humlib version).

**Comment by craigsapp** [comment]
> Also note the beat will swallow the first line of the chorales kern that contain `!!!!SEGMENT....`

I will work on getting it to be output.   The Humdrum Extras tools initially were designed to suppress that line, but it is better not to do that.

**Comment by WolfgangDrescher** [comment]
Thanks, that helped me. I also noticed that the `beat` program seems to be a bit more sensible, so changing the command order did the trick for me as well:


```sh
humcat h://chorales/chor081.krn | beat -a | extractxx -f 1,4,5 | fb -ac
```

I'm not using `rid` here because I need to match the line index so that I can create a mapping to the corresponding line in the original kern source file.
