### ISSUE TITLE
Humextra regression test failures

### ISSUE THREAD

**Issue by MarcPerlman** [craigsapp/humextra#3]
I've been trying to install humextra on Mac OS 10.9.5.  

When I run make programs, I get several warnings and one error message:

![image](https://cloud.githubusercontent.com/assets/8423971/5994361/ed3872e4-aa3d-11e4-9e9a-defacc5ba806.png)

For the record, the warnings are:
![image](https://cloud.githubusercontent.com/assets/8423971/5994364/0d5d3762-aa3e-11e4-94dd-1fb77673b215.png)
![image](https://cloud.githubusercontent.com/assets/8423971/5994366/2599d31c-aa3e-11e4-98ce-6a0efaa7785a.png)
![image](https://cloud.githubusercontent.com/assets/8423971/5994367/2fd9e89e-aa3e-11e4-8541-4cb3cce14b1d.png)

Most of the regression tests succeed, but there is one failure (sample):
![image](https://cloud.githubusercontent.com/assets/8423971/5994370/962ec22c-aa3e-11e4-95a1-c1badd428dbb.png)

However, not all of the utilities were tested.  I noticed that rscale was missing.  I looked for it in the humextra directory and didn't see it, nor did I find anything alphabetically beyond 'p'.  

Humextra/bin has the following files:

bin $ ls -lt
total 59296
-rwxr-xr-x  1 root  wheel  682664 Feb  1 17:39 prange
-rwxr-xr-x  1 root  wheel  664700 Feb  1 17:39 prettystar
-rwxr-xr-x  1 root  wheel  336116 Feb  1 17:39 pae2kern
-rwxr-xr-x  1 root  wheel  677684 Feb  1 17:39 pitchmix
-rwxr-xr-x  1 root  wheel  642928 Feb  1 17:39 ottava
-rwxr-xr-x  1 root  wheel  660728 Feb  1 17:39 notearray
-rwxr-xr-x  1 root  wheel  642920 Feb  1 17:39 onset
-rwxr-xr-x  1 root  wheel  711848 Feb  1 17:39 myank
-rwxr-xr-x  1 root  wheel  638856 Feb  1 17:39 mvspine
-rwxr-xr-x  1 root  wheel  765828 Feb  1 17:39 mkeyscape
-rwxr-xr-x  1 root  wheel  710228 Feb  1 17:39 mid2hum
-rwxr-xr-x  1 root  wheel  656640 Feb  1 17:39 minrhy
-rwxr-xr-x  1 root  wheel  638644 Feb  1 17:39 matphrase
-rwxr-xr-x  1 root  wheel  656528 Feb  1 17:39 melseq
-rwxr-xr-x  1 root  wheel  700104 Feb  1 17:39 lofcog
-rwxr-xr-x  1 root  wheel  678592 Feb  1 17:39 keycor
-rwxr-xr-x  1 root  wheel  661096 Feb  1 17:39 location
-rwxr-xr-x  1 root  wheel  656688 Feb  1 17:39 kern2melisma
-rwxr-xr-x  1 root  wheel  643028 Feb  1 17:39 kern2skini
-rwxr-xr-x  1 root  wheel  643152 Feb  1 17:39 kern2cmn
-rwxr-xr-x  1 root  wheel  643192 Feb  1 17:39 kern2dm
-rwxr-xr-x  1 root  wheel  657180 Feb  1 17:39 humsplit
-rwxr-xr-x  1 root  wheel  669520 Feb  1 17:39 humtable
-rwxr-xr-x  1 root  wheel  660944 Feb  1 17:39 humcat
-rwxr-xr-x  1 root  wheel  669272 Feb  1 17:39 humpdf
-rwxr-xr-x  1 root  wheel  677308 Feb  1 17:39 hum2xml
-rwxr-xr-x  1 root  wheel  942452 Feb  1 17:39 hum2muse
-rwxr-xr-x  1 root  wheel  778788 Feb  1 17:39 hum2mid
-rwxr-xr-x  1 root  wheel  693140 Feb  1 17:39 hum2mei
-rwxr-xr-x  1 root  wheel  647636 Feb  1 17:39 hum2gmn
-rwxr-xr-x  1 root  wheel  770544 Feb  1 17:39 hum2abc
-rwxr-xr-x  1 root  wheel  669532 Feb  1 17:39 hum2enp
-rwxr-xr-x  1 root  wheel  666024 Feb  1 17:39 hgrep
-rwxr-xr-x  1 root  wheel  669296 Feb  1 17:39 gettime
-rwxr-xr-x  1 root  wheel  665208 Feb  1 17:39 harm2kern
-rwxr-xr-x  1 root  wheel  695148 Feb  1 17:39 extractx
-rwxr-xr-x  1 root  wheel  660692 Feb  1 17:39 dittox
-rwxr-xr-x  1 root  wheel  709672 Feb  1 17:39 cint
-rwxr-xr-x  1 root  wheel  665276 Feb  1 17:39 blank
-rwxr-xr-x  1 root  wheel  668936 Feb  1 17:39 chorck
-rwxr-xr-x  1 root  wheel  643064 Feb  1 17:39 barnum
-rwxr-xr-x  1 root  wheel  678752 Feb  1 17:39 beat
-rwxr-xr-x  1 root  wheel  673984 Feb  1 17:39 autostem
-rwxr-xr-x  1 root  wheel  664912 Feb  1 17:39 barline
-rwxr-xr-x  1 root  wheel  647168 Feb  1 17:39 autodynam
lrwxr-xr-x  1 root  wheel      24 Feb  1 17:39 partjoin -> ../scripts/perl/partjoin
lrwxr-xr-x  1 root  wheel      25 Feb  1 17:39 sortcount -> ../scripts/perl/sortcount
bin $

It looks like the installation failed on proll and then skipped all the subsequent installations.

Is this a problem with an out-of-date compiler?  I don't know how to determine what versions I have:

bin $ ls -lt /usr/bin/g++
-rwxr-xr-x  1 root  wheel  14224 Aug  6 03:02 /usr/bin/g++
bin $ ls -lt /usr/bin/gcc
-rwxr-xr-x  1 root  wheel  14224 Aug  6 03:02 /usr/bin/gcc

Any advice would be appreciated; it's frustrating to be limited to only the first half of the alphabet when using humextras.

Thanks,
Marc Perlman

**Comment by craigsapp** [comment]
The problems related to this issue should now be fixed.  To update the code, if you are installing with humdrum-tools:

```
cd humdrum-tools    # go to the base directory of humdrum-tools wherever that is
make update         # this will update the submodules, humextra being one of them
cd humextra; make
# or
make humextra
```

Either of the last two commands should compile the humextra code, and hopefully the `proll` program should now compile without an error.

**1. Compiling error for proll**

The compiling error for `proll` should now be fixed.  The basic problem is that the compiler your are using is more strict about arrays created with sizes that come from variables.  You probably have an up-to-date compiler&mdash;the problem also occurs on my computer, but I must not have compiled this program recently with a newer compiler version (proll used to compile without errors...).  I adjusted the code to avoid this problem (The old code seems to have been informally allowed in C++ for a quite a while, but the newer compiler version seems to have omitted this feature, probably because it was not added to C++14 standard).

**2. Compiler warnings**

I see these compiler warnings too.  I don't care, as long at they are not errors :-)  I think I just fixed the first one which was technically an error, but the error produces the same result as the correct code.  There is a similar warning elsewhere in another program, but I don't see the problem in that case.

For second the warning, it seems to be related to an accented character, but this warning does not seem to cause problems and I don't now how to otherwise fix it to avoid seeing the warning.  

For the third warning, the compiler was complaining about extra parenthses: `if ((i==blackend)) {` which should better be `if (i==blackend) {`. Those are equivalent and should not cause problem&mdash;I'll fix that sometime in the future when I get annoyed enough seeing that warning.

**3. Regression test failure for sample**

For this regression test, the problem seems to be that you have a program in your command path called `sample` which shadows the humextras one.  Type `which sample` to see where it is located.  This will only be a problem if you want to use the sample program.  One solution is to rename humextra/bin/sample to humextra/bin/samplex, and then use `samplex` instead of `sample`.  The regression tests in examples/sample would have to be adjusted and moved to examples/samplex if you want them to pass.  Another possibility is that you can adjust your shell $PATH variable so that the humextra command path occurs before the one that has the other `sample` in it.  But in that case, the non-humextra `sample` command would be hidden by the humextra one.  I'll think about renaming `sample` to `samplex`, since "sample" is a common word, making it more likely to have a command-name collision in the future with other computer configurations, not just on your computer.

**4. Missing regression tests for some programs**

Some of the programs cannot produce the same result each time, mostly related to randomness such as pitchmix, which produces a different output every time:

```
pitchmix h://chorales/chor001.krn
```

If I add a random-seeding option to the program, this could be put into the regression test list (which would be good to do sometime).

For other programs, I might not have gotten around to adding regression tests..., but I think your main problem was the lack of commands after proll compiling failed.  271 tests are currently passing and one is currently failing for me (hum2muse test 001) which mostly has a trivial timestamp difference I will have to adjust the test to ignore.

**5. missing compiled programs starting with the letters p&ndash;z**

This problem was related to the compiler error for proll.  If proll is compiling correctly now, then compiling of all other programs should be successful.  I am counting 77 compiled programs total (two are actually PERL programs linked from the scripts/perl directory).

**Comment by MarcPerlman** [comment]
The sample program that is shadowing the Humextra program is in
/usr/bin/sample.  According to the man page, it seems to be a BSD built-in:

man sample

sample(1)                 BSD General Commands Manual
sample(1)

*NAME*

     *sample* -- Profile a process during a time interval

*SYNOPSIS*

     *sample* pid | partial-executable-name [duration [samplingInterval]] [
*-wait*] [*-mayDie*] [*-fullPaths*] [*-e*] [*-file* filename]

*DESCRIPTION*

     *sample* is a command-line tool for gathering data about the running
behavior of a process.  It suspends the process at specified intervals (by
default, every 1 millisecond), records the call stacks of all threads in
the process at that time, then resumes the process.  The analysis done by
*sample* is called ``sampling'' because it only checks the state of the
program at the sampling points.  The analysis may miss execution of some
functions that are not executing during one of the samples, but *sample*
still provides useful data about commonly executing functions.

     At the end of the sampling duration, *sample* produces a report
showing which functions were executing during the sampling.  The data is
condensed into a call tree, showing the functions seen on the stack and how
they were called.  ...


*3. Regression test failure for sample*
>
> For this regression test, the problem seems to be that you have a program
> in your command path called sample which shadows the humextras one. Type which
> sample to see where it is located. This will only be a problem if you
> want to use the sample program. One solution is to rename
> humextra/bin/sample to humextra/bin/samplex, and then use samplex instead
> of sample. The regression tests in examples/sample would have to be
> adjusted and moved to examples/samplex if you want them to pass. Another
> possibility is that you can adjust your shell $PATH variable so that the
> humextra command path occurs before the one that has the other sample in
> it. But in that case, the non-humextra sample command would be hidden by
> the humextra one. I'll think about renaming sample to samplex, since
> "sample" is a common word, making it more likely to have a command-name
> collision in the future with other computer configurations, not just on
> your computer.
>
>
> --
Associate Professor
Department of Music
Brown University
Providence, Rhode Island 02912
USA

http://research.brown.edu/research/profile.php?id=10308

*Unplayed Melodies: Javanese Gamelan and the Genesis of Music Theory*
http://www.ucpress.edu/book.php?isbn=9780520239562

"From 'Folklore' to 'Knowledge' in Global Governance: On the Metamorphoses
of the Unauthored"
http://www.sfu.ca/kbipinch/records/2705/
http://books.google.com/books?isbn=0226907090

**Comment by MarcPerlman** [comment]
Thanks!

Will this also install humplay?

On Mon, Feb 2, 2015 at 4:37 AM, Craig Stuart Sapp <notifications@github.com>
wrote:

> The problems related to this issue should now be fixed. To update the
> code, if you are installing with humdrum-tools:
>
> cd humdrum-tools    # go to the base directory of humdrum-tools wherever that is
> make update         # this will update the submodules, humextra being one of them
> cd humextra; make
> # or
> make humextra
>
> Either of the last two commands should compile the humextra code, and
> hopefully the proll program should now compile without an error.
>
>
>
-- 
Associate Professor
Department of Music
Brown University
Providence, Rhode Island 02912
USA

http://research.brown.edu/research/profile.php?id=10308

*Unplayed Melodies: Javanese Gamelan and the Genesis of Music Theory*
http://www.ucpress.edu/book.php?isbn=9780520239562

"From 'Folklore' to 'Knowledge' in Global Governance: On the Metamorphoses
of the Unauthored"
http://www.sfu.ca/kbipinch/records/2705/
http://books.google.com/books?isbn=0226907090

**Comment by craigsapp** [comment]
To compile humplay there are a couple of commands you have to run:

```
cd ~/humdrum-tools
git clone https://github.com/craigsapp/improv
cd improv
make library
cd ../humextra
make humplay
```

These commands download the improv library which I use to talk to MIDI, then compile the improv library, and then you go back to the humextra submodule and compile the humplay command.  This should create the program `~/humdrum-tools/humextra/bin/humplay`.

If you have already installed the `~/humdrum-tools/humextra/bin` directory in your search path, i.e., if you see that path when you type:
```
echo $PATH
```
Then it should be ready to use.  I just tested it and it is compiling and working in OS X (at least for me :-).  The only **caveat** is that you have to plug the mac into an external synthesizer, as I don't know how to talk to an internal synth in OS X.  When you start humplay it will ask you for a particular input and output port to play the MIDI on.  The input port is not used so you can choose any if there is more than one listed.  For the output ports, you can try each one of them if there are more than one, and one of them should work. 

There is an option:
```
humplay --ports
``` 
which will list all of the available ports.  On my OS X laptop, I see this list:
```
humplay --ports

MIDI input ports: 2
	0: 
	1: 

MIDI output ports: 2
	0: Port A:M-Audio:MIDISPORT 2x2
	1: Port B:M-Audio:MIDISPORT 2x2
```

And MIDI output port 0 is the one that I get sound on (the cable that is connected to the external synth).

**Comment by craigsapp** [comment]
For /usr/bin/sample, I see that I also have that program on my computer.  I always put the humextras and humdrum bin directories at the start of the list, and I never noticed that it was shadowing the /usr/bin/sample program (which I never used).  So the easiest short-term solution is to rename humextra/bin/sample to humextra/bin/samplex.  Another alternative is that you can adjust the path so that  humdrum directories have priority when searching for commands.

Here is how I phrased `/etc/profile.d/humdrum.sh`:

```
   PATH=".:/usr/local/humdrum-tools/humextra/bin:/usr/local/humdrum-tools/humdrum/bin:$PATH"
```

I.e., the search path starts in the current directory.  If the command is not found there, then try ...humextra/bin, then ...humdrum/bin, then whatever the original PATH variable was set to.

In the long term, I will probably rename the `sample` program to be `samplex` so that that name collision does not happen.
